### PR TITLE
Config classes

### PR DESCRIPTION
**Pull request by bruny**
Use class definitions in config.py to allow code reuse
If validation fails for a rom collection, skip the collection rather
than fail the entire config
Add unit tests and test data for validation of reading config file

### CODE REVIEW

**Comment by bruny** [comment]
The main change for this specific PR is:
- resources/lib/config.py
- resources/lib/tests/test_configxml.py
- resources/lib/tests/testdata/config.xml

**Comment by bruny** [comment]
Apologies accidentally deleted the branch; PR still valid.

**Comment by maloep** [comment]
Hi,

thanks again for your PRs. I have next to zero time these days but I hope that I am able to catch up soon. Will check everything and include it if it works.

Regards,
Malte

**Comment by bruny** [comment]
Actually, reviewing this PR, I'm not happy with the changes I've made. I'm going to rework and resubmit it, so I'm closing for now.

**Pull request closed without merging**
